name: Send Contact Email

on:
  repository_dispatch:
    types: [contact-form]

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install @sendgrid/mail

      - name: Send email via SendGrid
        env:
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
          CONTACT_EMAIL: ${{ secrets.CONTACT_EMAIL }}
        run: |
          node -e "
          const sgMail = require('@sendgrid/mail');
          const fs = require('fs');
          const { SENDGRID_API_KEY, FROM_EMAIL, CONTACT_EMAIL } = process.env;
          
          if (!SENDGRID_API_KEY || !FROM_EMAIL || !CONTACT_EMAIL) {
            console.error('Missing required environment variables');
            process.exit(1);
          }
          
          sgMail.setApiKey(SENDGRID_API_KEY);
          
          // Read the GitHub event payload
          let eventData = {};
          try {
            const eventPath = process.env.GITHUB_EVENT_PATH;
            if (eventPath && fs.existsSync(eventPath)) {
              const eventContent = fs.readFileSync(eventPath, 'utf8');
              eventData = JSON.parse(eventContent);
            }
          } catch (error) {
            console.error('Error reading GitHub event:', error);
            process.exit(1);
          }
          
          const { client_payload } = eventData;
          const { name, email, subject, message } = client_payload || {};
          
          if (!name || !email || !subject || !message) {
            console.error('Missing required form data:', { name, email, subject, message });
            process.exit(1);
          }
          
          const msg = {
            to: CONTACT_EMAIL,
            from: FROM_EMAIL,
            subject: \`Contact Form: \${subject}\`,
            text: \`Name: \${name}\nEmail: \${email}\nSubject: \${subject}\nMessage: \${message}\`,
            html: \`
              <h2>New Contact Form Submission</h2>
              <p><strong>Name:</strong> \${name}</p>
              <p><strong>Email:</strong> \${email}</p>
              <p><strong>Subject:</strong> \${subject}</p>
              <p><strong>Message:</strong></p>
              <p>\${message.replace(/\n/g, '<br>')}</p>
            \`
          };
          
          sgMail.send(msg)
            .then(() => {
              console.log('Email sent successfully');
            })
            .catch((error) => {
              console.error('Error sending email:', error);
              process.exit(1);
            });
          "
