name: Send Contact Email

on:
  repository_dispatch:
    types: [contact-form]

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd railway-backend
          npm install

      - name: Send email via SendGrid
        env:
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
          CONTACT_EMAIL: ${{ secrets.CONTACT_EMAIL }}
        run: |
          cd railway-backend
          node -e "
          const sgMail = require('@sendgrid/mail');
          const { SENDGRID_API_KEY, FROM_EMAIL, CONTACT_EMAIL } = process.env;
          
          if (!SENDGRID_API_KEY || !FROM_EMAIL || !CONTACT_EMAIL) {
            console.error('Missing required environment variables');
            process.exit(1);
          }
          
          sgMail.setApiKey(SENDGRID_API_KEY);
          
          const { client_payload } = JSON.parse(process.env.GITHUB_EVENT_PATH || '{}');
          const { name, email, subject, message } = client_payload || {};
          
          if (!name || !email || !subject || !message) {
            console.error('Missing required form data');
            process.exit(1);
          }
          
          const msg = {
            to: CONTACT_EMAIL,
            from: FROM_EMAIL,
            subject: \`Contact Form: \${subject}\`,
            text: \`Name: \${name}\nEmail: \${email}\nSubject: \${subject}\nMessage: \${message}\`,
            html: \`
              <h2>New Contact Form Submission</h2>
              <p><strong>Name:</strong> \${name}</p>
              <p><strong>Email:</strong> \${email}</p>
              <p><strong>Subject:</strong> \${subject}</p>
              <p><strong>Message:</strong></p>
              <p>\${message.replace(/\n/g, '<br>')}</p>
            \`
          };
          
          sgMail.send(msg)
            .then(() => {
              console.log('Email sent successfully');
            })
            .catch((error) => {
              console.error('Error sending email:', error);
              process.exit(1);
            });
          "
